"""add persistent identifiers

Revision ID: 16aa345cd01b
Revises: 722053fac80b
Create Date: 2026-10-05 17:10:41.982157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '16aa345cd01b'
down_revision: Union[str, Sequence[str], None] = '722053fac80b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('persistent_identifier', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('dataset', sa.Column('persistent_identifier', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('device', sa.Column('persistent_identifier', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('shot', sa.Column('persistent_identifier', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('source', sa.Column('persistent_identifier', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source', 'persistent_identifier')
    op.drop_column('shot', 'persistent_identifier')
    op.drop_column('device', 'persistent_identifier')
    op.drop_column('dataset', 'persistent_identifier')
    op.drop_column('collection', 'persistent_identifier')
    # ### end Alembic commands ###
