"""initial schema

Revision ID: 2419cd702b7d
Revises:
Create Date: 2026-09-22 16:40:15.558791

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2419cd702b7d"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "device",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("publisher", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("creator", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "began_operations", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "access_level",
            sa.Enum("PUBLIC", "RESTRICTED", "EMBARGOED", name="accesslevel"),
            nullable=True,
        ),
        sa.Column("required_scopes", sa.JSON(), nullable=True),
        sa.Column("allowed_idps", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_device_access_level"), "device", ["access_level"], unique=False
    )
    op.create_index(
        op.f("ix_device_created_at"), "device", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_device_creator"), "device", ["creator"], unique=False)
    op.create_index(op.f("ix_device_id"), "device", ["id"], unique=False)
    op.create_index(op.f("ix_device_name"), "device", ["name"], unique=True)
    op.create_index(op.f("ix_device_publisher"), "device", ["publisher"], unique=False)
    op.create_index(op.f("ix_device_status"), "device", ["status"], unique=False)
    op.create_index(op.f("ix_device_title"), "device", ["title"], unique=False)
    op.create_index(op.f("ix_device_type"), "device", ["type"], unique=False)
    op.create_index(
        op.f("ix_device_updated_at"), "device", ["updated_at"], unique=False
    )
    op.create_table(
        "shot",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("scientific_metadata", sa.JSON(), nullable=True),
        sa.Column("shot_at", sa.DateTime(), nullable=True),
        sa.Column("shot_end", sa.DateTime(), nullable=True),
        sa.Column("shot_duration", sa.Float(), nullable=True),
        sa.Column("t0_at", sa.DateTime(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("publisher", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("creator", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "access_level",
            sa.Enum("PUBLIC", "RESTRICTED", "EMBARGOED", name="accesslevel"),
            nullable=True,
        ),
        sa.Column("required_scopes", sa.JSON(), nullable=True),
        sa.Column("allowed_idps", sa.JSON(), nullable=True),
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("device_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_name"],
            ["device.name"],
        ),
        sa.PrimaryKeyConstraint("device_name", "id"),
    )
    op.create_index(
        op.f("ix_shot_access_level"), "shot", ["access_level"], unique=False
    )
    op.create_index(op.f("ix_shot_created_at"), "shot", ["created_at"], unique=False)
    op.create_index(op.f("ix_shot_creator"), "shot", ["creator"], unique=False)
    op.create_index(op.f("ix_shot_device_name"), "shot", ["device_name"], unique=False)
    op.create_index(op.f("ix_shot_publisher"), "shot", ["publisher"], unique=False)
    op.create_index(op.f("ix_shot_shot_at"), "shot", ["shot_at"], unique=False)
    op.create_index(op.f("ix_shot_shot_end"), "shot", ["shot_end"], unique=False)
    op.create_index(op.f("ix_shot_updated_at"), "shot", ["updated_at"], unique=False)
    op.create_table(
        "source",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum(
                "SOFTWARE", "INSTRUMENT", "PERSON", "ORGANIZATION", name="sourcekind"
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["device.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_source_kind"), "source", ["kind"], unique=False)
    op.create_index(op.f("ix_source_name"), "source", ["name"], unique=True)
    op.create_table(
        "activity",
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.Column("source_version", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "activity_type",
            sa.Enum(
                "MEASUREMENT",
                "SIMULATION",
                "ANALYSIS",
                "CALIBRATION",
                name="activitytype",
            ),
            nullable=True,
        ),
        sa.Column("parameters", sa.JSON(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "activityagent",
        sa.Column("activity_id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("EXECUTOR", "ORCHESTRATOR", name="agentrole"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activity.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
        ),
        sa.PrimaryKeyConstraint("activity_id", "source_id"),
    )
    op.create_table(
        "activitydelegation",
        sa.Column("activity_id", sa.Integer(), nullable=False),
        sa.Column("subordinate_source_id", sa.Integer(), nullable=False),
        sa.Column("responsible_source_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activity.id"],
        ),
        sa.ForeignKeyConstraint(
            ["responsible_source_id"],
            ["source.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subordinate_source_id"],
            ["source.id"],
        ),
        sa.PrimaryKeyConstraint(
            "activity_id", "subordinate_source_id", "responsible_source_id"
        ),
    )
    op.create_table(
        "activityinstrument",
        sa.Column("activity_id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activity.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
        ),
        sa.PrimaryKeyConstraint("activity_id", "source_id"),
    )
    op.create_table(
        "collection",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("scientific_metadata", sa.JSON(), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("publisher", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("creator", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("device_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "access_level",
            sa.Enum("PUBLIC", "RESTRICTED", "EMBARGOED", name="accesslevel"),
            nullable=True,
        ),
        sa.Column("root_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("required_scopes", sa.JSON(), nullable=True),
        sa.Column("allowed_idps", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("shot_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("activity_id", sa.Integer(), nullable=True),
        sa.Column("origin", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activity.id"],
        ),
        sa.ForeignKeyConstraint(
            ["device_name", "shot_id"],
            ["shot.device_name", "shot.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "device_name", "shot_id", "name", name="idx_collection_context_name"
        ),
    )
    op.create_index(
        op.f("ix_collection_access_level"), "collection", ["access_level"], unique=False
    )
    op.create_index(
        op.f("ix_collection_activity_id"), "collection", ["activity_id"], unique=False
    )
    op.create_index(
        op.f("ix_collection_created_at"), "collection", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_collection_creator"), "collection", ["creator"], unique=False
    )
    op.create_index(
        op.f("ix_collection_device_name"), "collection", ["device_name"], unique=False
    )
    op.create_index(op.f("ix_collection_name"), "collection", ["name"], unique=False)
    op.create_index(
        op.f("ix_collection_origin"), "collection", ["origin"], unique=False
    )
    op.create_index(
        op.f("ix_collection_publisher"), "collection", ["publisher"], unique=False
    )
    op.create_index(
        op.f("ix_collection_shot_id"), "collection", ["shot_id"], unique=False
    )
    op.create_index(op.f("ix_collection_title"), "collection", ["title"], unique=False)
    op.create_index(
        op.f("ix_collection_updated_at"), "collection", ["updated_at"], unique=False
    )
    op.create_table(
        "dataset",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("scientific_metadata", sa.JSON(), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("publisher", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("creator", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=True),
        sa.Column("quality_flag", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("temporal_start", sa.DateTime(), nullable=True),
        sa.Column("temporal_end", sa.DateTime(), nullable=True),
        sa.Column("device_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "access_level",
            sa.Enum("PUBLIC", "RESTRICTED", "EMBARGOED", name="accesslevel"),
            nullable=True,
        ),
        sa.Column("license", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("version", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("keywords", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("required_scopes", sa.JSON(), nullable=True),
        sa.Column("allowed_idps", sa.JSON(), nullable=True),
        sa.Column("geometry_references", sa.JSON(), nullable=True),
        sa.Column("geometry_roles", sa.JSON(), nullable=True),
        sa.Column("calibration_references", sa.JSON(), nullable=True),
        sa.Column("calibration_roles", sa.JSON(), nullable=True),
        sa.Column("calibration_stage", sa.Integer(), nullable=True),
        sa.Column("applies_to", sa.JSON(), nullable=True),
        sa.Column("annotates", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("shot_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("activity_id", sa.Integer(), nullable=True),
        sa.Column("subject_dataset_id", sa.Integer(), nullable=True),
        sa.Column("origin", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activity.id"],
        ),
        sa.ForeignKeyConstraint(
            ["device_name", "shot_id"],
            ["shot.device_name", "shot.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subject_dataset_id"],
            ["dataset.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_dataset_unique_federated",
        "dataset",
        ["name", "device_name", "shot_id", "origin"],
        unique=True,
        postgresql_where=sa.text("activity_id IS NULL AND origin IS NOT NULL"),
    )
    op.create_index(
        "idx_dataset_unique_local",
        "dataset",
        ["name", "device_name", "shot_id"],
        unique=True,
        postgresql_where=sa.text("activity_id IS NULL AND origin IS NULL"),
    )
    op.create_index(
        "idx_dataset_unique_with_activity",
        "dataset",
        ["name", "device_name", "shot_id", "activity_id"],
        unique=True,
        postgresql_where=sa.text("activity_id IS NOT NULL"),
    )
    op.create_index(
        op.f("ix_dataset_access_level"), "dataset", ["access_level"], unique=False
    )
    op.create_index(
        op.f("ix_dataset_activity_id"), "dataset", ["activity_id"], unique=False
    )
    op.create_index(
        op.f("ix_dataset_annotates"), "dataset", ["annotates"], unique=False
    )
    op.create_index(
        op.f("ix_dataset_created_at"), "dataset", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_dataset_creator"), "dataset", ["creator"], unique=False)
    op.create_index(
        op.f("ix_dataset_device_name"), "dataset", ["device_name"], unique=False
    )
    op.create_index(op.f("ix_dataset_level"), "dataset", ["level"], unique=False)
    op.create_index(op.f("ix_dataset_name"), "dataset", ["name"], unique=False)
    op.create_index(op.f("ix_dataset_origin"), "dataset", ["origin"], unique=False)
    op.create_index(
        op.f("ix_dataset_publisher"), "dataset", ["publisher"], unique=False
    )
    op.create_index(
        op.f("ix_dataset_quality_flag"), "dataset", ["quality_flag"], unique=False
    )
    op.create_index(op.f("ix_dataset_shot_id"), "dataset", ["shot_id"], unique=False)
    op.create_index(
        op.f("ix_dataset_subject_dataset_id"),
        "dataset",
        ["subject_dataset_id"],
        unique=False,
    )
    op.create_index(op.f("ix_dataset_title"), "dataset", ["title"], unique=False)
    op.create_index(
        op.f("ix_dataset_updated_at"), "dataset", ["updated_at"], unique=False
    )
    op.create_index(op.f("ix_dataset_version"), "dataset", ["version"], unique=False)
    op.create_table(
        "activityinput",
        sa.Column("activity_id", sa.Integer(), nullable=False),
        sa.Column("dataset_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activity.id"],
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["dataset.id"],
        ),
        sa.PrimaryKeyConstraint("activity_id", "dataset_id"),
    )
    op.create_table(
        "collectiondataset",
        sa.Column("collection_id", sa.Integer(), nullable=False),
        sa.Column("dataset_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collection.id"],
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["dataset.id"],
        ),
        sa.PrimaryKeyConstraint("collection_id", "dataset_id"),
    )
    op.create_table(
        "collectionmember",
        sa.Column("parent_id", sa.Integer(), nullable=False),
        sa.Column("child_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["child_id"],
            ["collection.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["collection.id"],
        ),
        sa.PrimaryKeyConstraint("parent_id", "child_id"),
    )
    op.create_table(
        "datasetderivation",
        sa.Column("source_dataset_id", sa.Integer(), nullable=True),
        sa.Column(
            "source_identifier", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("source_label", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "source_description", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dataset_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["dataset.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_dataset_id"],
            ["dataset.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_datasetderivation_dataset_id"),
        "datasetderivation",
        ["dataset_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_datasetderivation_source_dataset_id"),
        "datasetderivation",
        ["source_dataset_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_datasetderivation_source_identifier"),
        "datasetderivation",
        ["source_identifier"],
        unique=False,
    )
    op.create_table(
        "distribution",
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("endpoint_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("region", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("media_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("format", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "access_level",
            sa.Enum("PUBLIC", "RESTRICTED", "EMBARGOED", name="accesslevel"),
            nullable=True,
        ),
        sa.Column("default_distribution", sa.Boolean(), nullable=False),
        sa.Column(
            "storage_options_type",
            sa.Enum("FSSPEC_S3", "ICECHUNK_S3", name="storageoptionstype"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dataset_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["dataset_id"], ["dataset.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_distribution_dataset_id"), "distribution", ["dataset_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_distribution_dataset_id"), table_name="distribution")
    op.drop_table("distribution")
    op.drop_index(
        op.f("ix_datasetderivation_source_identifier"), table_name="datasetderivation"
    )
    op.drop_index(
        op.f("ix_datasetderivation_source_dataset_id"), table_name="datasetderivation"
    )
    op.drop_index(
        op.f("ix_datasetderivation_dataset_id"), table_name="datasetderivation"
    )
    op.drop_table("datasetderivation")
    op.drop_table("collectionmember")
    op.drop_table("collectiondataset")
    op.drop_table("activityinput")
    op.drop_index(op.f("ix_dataset_version"), table_name="dataset")
    op.drop_index(op.f("ix_dataset_updated_at"), table_name="dataset")
    op.drop_index(op.f("ix_dataset_title"), table_name="dataset")
    op.drop_index(op.f("ix_dataset_subject_dataset_id"), table_name="dataset")
    op.drop_index(op.f("ix_dataset_shot_id"), table_name="dataset")
    op.drop_index(op.f("ix_dataset_quality_flag"), table_name="dataset")
    op.drop_index(op.f("ix_dataset_publisher"), table_name="dataset")
    op.drop_index(op.f("ix_dataset_origin"), table_name="dataset")
    op.drop_index(op.f("ix_dataset_name"), table_name="dataset")
    op.drop_index(op.f("ix_dataset_level"), table_name="dataset")
    op.drop_index(op.f("ix_dataset_device_name"), table_name="dataset")
    op.drop_index(op.f("ix_dataset_creator"), table_name="dataset")
    op.drop_index(op.f("ix_dataset_created_at"), table_name="dataset")
    op.drop_index(op.f("ix_dataset_annotates"), table_name="dataset")
    op.drop_index(op.f("ix_dataset_activity_id"), table_name="dataset")
    op.drop_index(op.f("ix_dataset_access_level"), table_name="dataset")
    op.drop_index(
        "idx_dataset_unique_with_activity",
        table_name="dataset",
        postgresql_where=sa.text("activity_id IS NOT NULL"),
    )
    op.drop_index(
        "idx_dataset_unique_local",
        table_name="dataset",
        postgresql_where=sa.text("activity_id IS NULL AND origin IS NULL"),
    )
    op.drop_index(
        "idx_dataset_unique_federated",
        table_name="dataset",
        postgresql_where=sa.text("activity_id IS NULL AND origin IS NOT NULL"),
    )
    op.drop_table("dataset")
    op.drop_index(op.f("ix_collection_updated_at"), table_name="collection")
    op.drop_index(op.f("ix_collection_title"), table_name="collection")
    op.drop_index(op.f("ix_collection_shot_id"), table_name="collection")
    op.drop_index(op.f("ix_collection_publisher"), table_name="collection")
    op.drop_index(op.f("ix_collection_origin"), table_name="collection")
    op.drop_index(op.f("ix_collection_name"), table_name="collection")
    op.drop_index(op.f("ix_collection_device_name"), table_name="collection")
    op.drop_index(op.f("ix_collection_creator"), table_name="collection")
    op.drop_index(op.f("ix_collection_created_at"), table_name="collection")
    op.drop_index(op.f("ix_collection_activity_id"), table_name="collection")
    op.drop_index(op.f("ix_collection_access_level"), table_name="collection")
    op.drop_table("collection")
    op.drop_table("activityinstrument")
    op.drop_table("activitydelegation")
    op.drop_table("activityagent")
    op.drop_table("activity")
    op.drop_index(op.f("ix_source_name"), table_name="source")
    op.drop_index(op.f("ix_source_kind"), table_name="source")
    op.drop_table("source")
    op.drop_index(op.f("ix_shot_updated_at"), table_name="shot")
    op.drop_index(op.f("ix_shot_shot_end"), table_name="shot")
    op.drop_index(op.f("ix_shot_shot_at"), table_name="shot")
    op.drop_index(op.f("ix_shot_publisher"), table_name="shot")
    op.drop_index(op.f("ix_shot_device_name"), table_name="shot")
    op.drop_index(op.f("ix_shot_creator"), table_name="shot")
    op.drop_index(op.f("ix_shot_created_at"), table_name="shot")
    op.drop_index(op.f("ix_shot_access_level"), table_name="shot")
    op.drop_table("shot")
    op.drop_index(op.f("ix_device_updated_at"), table_name="device")
    op.drop_index(op.f("ix_device_type"), table_name="device")
    op.drop_index(op.f("ix_device_title"), table_name="device")
    op.drop_index(op.f("ix_device_status"), table_name="device")
    op.drop_index(op.f("ix_device_publisher"), table_name="device")
    op.drop_index(op.f("ix_device_name"), table_name="device")
    op.drop_index(op.f("ix_device_id"), table_name="device")
    op.drop_index(op.f("ix_device_creator"), table_name="device")
    op.drop_index(op.f("ix_device_created_at"), table_name="device")
    op.drop_index(op.f("ix_device_access_level"), table_name="device")
    op.drop_table("device")
    # ### end Alembic commands ###
    # Enum types outlive the tables that used them, so a downgrade that left
    # them behind could not be re-applied.
    op.execute("DROP TYPE IF EXISTS accesslevel")
    op.execute("DROP TYPE IF EXISTS activitytype")
    op.execute("DROP TYPE IF EXISTS agentrole")
    op.execute("DROP TYPE IF EXISTS sourcekind")
    op.execute("DROP TYPE IF EXISTS storageoptionstype")
