"""drop distribution access_level

Revision ID: 90dc7759b6f8
Revises: fbdc468a3bc1
Create Date: 2026-10-08 08:19:37.573454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90dc7759b6f8'
down_revision: Union[str, Sequence[str], None] = 'fbdc468a3bc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('distribution', 'access_level')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distribution', sa.Column('access_level', postgresql.ENUM('PUBLIC', 'RESTRICTED', 'EMBARGOED', name='accesslevel'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
