"""add issued date

Revision ID: a0f1e0e42705
Revises: 16aa345cd01b
Create Date: 2026-10-05 18:06:39.480821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a0f1e0e42705'
down_revision: Union[str, Sequence[str], None] = '16aa345cd01b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('issued', sa.Date(), nullable=True))
    op.add_column('dataset', sa.Column('issued', sa.Date(), nullable=True))
    op.add_column('shot', sa.Column('issued', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shot', 'issued')
    op.drop_column('dataset', 'issued')
    op.drop_column('collection', 'issued')
    # ### end Alembic commands ###
