"""add distribution conforms_to

Revision ID: dcb63fa997b3
Revises: 90dc7759b6f8
Create Date: 2026-10-09 19:51:22.255212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dcb63fa997b3'
down_revision: Union[str, Sequence[str], None] = '90dc7759b6f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distribution', sa.Column('conforms_to', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('distribution', 'conforms_to')
    # ### end Alembic commands ###
