"""add distribution group

Revision ID: fbdc468a3bc1
Revises: a0f1e0e42705
Create Date: 2026-10-06 15:09:44.998990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fbdc468a3bc1'
down_revision: Union[str, Sequence[str], None] = 'a0f1e0e42705'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distribution', sa.Column('group', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('distribution', 'group')
    # ### end Alembic commands ###
